### ISSUE TITLE
CraftCMS 5?

### ISSUE THREAD

**Issue by Kristomen** [behinddesign/craft-object-storage#1]
Is there a planned migration of the plugin to CraftCMS 5?

**Comment by obuchmann** [comment]
I made a PR: https://github.com/behinddesign/craft-object-storage/pull/2

@behinddesign please merge and publish a new version

**Comment by obuchmann** [comment]
@behinddesign would you be so kind to release it to the craft 5 store thanks!

**Comment by behinddesign** [comment]
Now showing as available for craft 5.
